# Generated by Django 3.0.3 on 2020-03-30 12:58

from django.db import migrations, models
import django.db.models.deletion
import pessoa.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sicupira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', pessoa.models.CICharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('numero_documento', models.CharField(max_length=20)),
                ('email', pessoa.models.CIEmailField(blank=True, max_length=254, null=True)),
                ('nacionalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NacionalidadePessoa', to='sicupira.Pais')),
                ('sexo', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SexoPessoa', to='sicupira.Sexo')),
                ('tipo_documento', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TipoDoc', to='sicupira.TipoDocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='PessoaDiscente', serialize=False, to='pessoa.Pessoa')),
                ('data_situacao', models.DateField()),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Curso', to='sicupira.Curso')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Nivel', to='sicupira.NivelGraduacao')),
                ('situacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SituacaoMatricula', to='sicupira.SituacaoMatricula')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='PessoaDocente', serialize=False, to='pessoa.Pessoa')),
                ('data_titulacao', models.DateField()),
                ('regime_trabalho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegimeTrabalhoDocente', to='sicupira.RegimeTrabalho')),
                ('titulo_nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TituloNivel', to='sicupira.NivelGraduacao')),
                ('titulo_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TituloPais', to='sicupira.Pais')),
                ('vinculo_ies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VinculoIESDocente', to='sicupira.VinculoIES')),
            ],
        ),
        migrations.CreateModel(
            name='Abreviatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_abreviatura', pessoa.models.CICharField(max_length=100)),
                ('flg_principal', models.BooleanField(default=False)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa', to='pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CategoriaDocente', to='sicupira.CategoriaDocente')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Instituicao', to='sicupira.Instituicao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Docente', to='pessoa.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Orienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_orientacao', models.DateField()),
                ('flg_principal', models.BooleanField(default=False)),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiscenteOrienta', to='pessoa.Discente')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocenteOrienta', to='pessoa.Docente')),
            ],
        ),
    ]
