# Generated by Django 2.2.10 on 2020-03-23 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sicupira', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(default='M', max_length=1)),
                ('data_nascimento', models.DateField()),
                ('numero_documento', models.CharField(max_length=20)),
                ('tipo_documento', models.IntegerField(default=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nacionalidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='NacionalidadePessoa', to='sicupira.Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Discente',
            fields=[
                ('pessoa_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoa.Pessoa')),
                ('data_situacao', models.DateField()),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Curso', to='sicupira.Curso')),
                ('nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Nivel', to='sicupira.NivelGraduacao')),
                ('situacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SituacaoMatricula', to='sicupira.SituacaoMatricula')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoa.Pessoa')),
                ('data_titulacao', models.DateField()),
                ('regime_trabalho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RegimeTrabalhoDocente', to='sicupira.RegimeTrabalho')),
                ('titulo_nivel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TituloNivel', to='sicupira.NivelGraduacao')),
                ('titulo_pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TituloPais', to='sicupira.Pais')),
                ('vinclulo_ies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='VincluloIESDocente', to='sicupira.VincluloIES')),
            ],
        ),
        migrations.CreateModel(
            name='Abreviatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_abreviatura', models.CharField(max_length=100)),
                ('flg_principal', models.IntegerField(default=0)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pessoa', to='pessoa.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CategoriaDocente', to='sicupira.CategoriaDocente')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Instituicao', to='sicupira.Instituicao')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Docente', to='pessoa.Docente')),
            ],
        ),
        migrations.CreateModel(
            name='Orienta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_orientacao', models.DateField()),
                ('flg_principal', models.IntegerField(default=0)),
                ('discente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiscenteOrienta', to='pessoa.Discente')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DocenteOrienta', to='pessoa.Docente')),
            ],
        ),
    ]
