# Generated by Django 2.2.10 on 2020-03-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orienta',
            name='flg_principal',
            field=models.BooleanField(default=False),
        ),
    ]
