# Generated by Django 3.0.3 on 2020-03-30 01:57

from django.db import migrations, models
import django.db.models.deletion
import pessoa.models


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0001_initial'),
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abreviatura',
            name='desc_abreviatura',
            field=pessoa.models.CICharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=pessoa.models.CIEmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=pessoa.models.CICharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tipo_documento',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TipoDoc', to='sicupira.TipoDocumento'),
        ),
    ]
