# Generated by Django 2.2.10 on 2020-03-24 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discente',
            old_name='pessoa_id',
            new_name='pessoa',
        ),
        migrations.AlterField(
            model_name='orienta',
            name='discente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiscenteOrienta', to='pessoa.Discente', to_field='pessoa_id'),
        ),
    ]
