# Generated by Django 2.2.10 on 2020-03-24 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0002_auto_20200323_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='vinclulo_ies',
            new_name='vinculo_ies',
        ),
        migrations.AlterField(
            model_name='orienta',
            name='discente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiscenteOrienta', to='pessoa.Discente'),
        ),
    ]
