# Generated by Django 3.0.3 on 2020-02-20 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cep', models.IntegerField()),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('ramal', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
