# Generated by Django 3.0.3 on 2020-02-23 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0002_auto_20200219_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cep', models.IntegerField()),
                ('logradouro', models.CharField(max_length=200)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('municipio', models.CharField(max_length=200)),
                ('fax', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('ramal', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.CharField(max_length=200)),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Instituicao',
        ),
        migrations.AddField(
            model_name='endereco',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sicupira.UF'),
        ),
    ]
