# Generated by Django 3.0.3 on 2020-03-08 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0004_auto_20200308_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='nome_turma',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
    ]
