# Generated by Django 3.0.3 on 2020-03-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0006_programa_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAvaliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_avaliacao', models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
