# Generated by Django 3.0.3 on 2020-03-09 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0007_areaavaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='area_avaliacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AreaAvaliacao', to='sicupira.AreaAvaliacao'),
        ),
    ]
