# Generated by Django 3.0.3 on 2020-03-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0008_programa_area_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecoprograma',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoprograma',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoprograma',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enderecoprograma',
            name='ramal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='codigo_cnpq',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
