# Generated by Django 3.0.3 on 2020-03-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0009_auto_20200309_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecoprograma',
            name='fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='flg_cooperacao',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='programa',
            name='flg_rede',
            field=models.BooleanField(null=True),
        ),
    ]
