# Generated by Django 3.0.3 on 2020-03-11 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0012_auto_20200310_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaBasica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc_area_basica', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='programa',
            name='area_basica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AreaBasicaPrograma', to='sicupira.AreaBasica'),
        ),
    ]
