# Generated by Django 3.0.3 on 2020-03-11 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0013_auto_20200310_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programa',
            name='linha_pesquisa_id',
        ),
        migrations.AlterField(
            model_name='programa',
            name='area_basica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='AreaBasica', to='sicupira.AreaBasica'),
        ),
    ]
