# Generated by Django 3.0.3 on 2020-03-12 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0014_auto_20200310_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DisciplinaCurso', to='sicupira.Disciplina'),
        ),
    ]
