# Generated by Django 3.0.3 on 2020-03-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0015_auto_20200311_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='disciplina',
            field=models.IntegerField(default=0),
        ),
    ]
