# Generated by Django 2.2.10 on 2020-03-12 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sicupira', '0016_auto_20200311_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='linhapesquisa',
            name='area_concentracao_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LinhaArea', to='sicupira.AreaConcentracao'),
        ),
        migrations.AddField(
            model_name='linhapesquisa',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='linhapesquisa',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='linhapesquisa',
            name='nome_linha_pesquisa',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='linhapesquisa',
            name='desc_linha_pesquisa',
            field=models.TextField(null=True),
        ),
    ]
